name: ci

on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.branch-name.outputs.is_default == 'true'
        id: docker_build
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: |
            jfnandopr/codenarc:latest
            jfnandopr/codenarc:1.0.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
